import './globals.css'
import Head from 'next/head';

export const BASE_URL = process.env.BASE_URL

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <meta property="og:title" content="Frame" />
        <meta property="og:image" content={`${BASE_URL}/question.jpg`} />
        <meta property="fc:frame" content="vNext" />
        <meta property="fc:frame:image" content={`${BASE_URL}/question.jpg`} />
        <meta property="fc:frame:button:1" content="COLOR" />
        <meta property="fc:frame:button:2" content="PASTA" />
        <meta property="fc:frame:post_url" content={`${BASE_URL}/api/post`} />
      </Head>

      <body>{children}</body>
    </html>
  )
}
